config/routes.rb
SoupToBits::Application.routes.draw do
root to: "categories#index"
resources :categories, :soups
get '/allcategories', to: redirect("/")
get '/soups/:id/toggle_featured', to: "soups#toggle_featured", as: :toggle_featured
get "/secret_soups", to: "soups#secret_soups"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :soups
end

app/models/soup.rb
class Soup < ActiveRecord::Base
	belongs_to :category
	validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :fetch_category, only: [:show, :update, :edit, :destroy]

	def index
    @categories = Category.all
    respond_to do |format|
      format.html
      format.json { render json: @categories }
    end
  end
  def show
    respond_to do |format|
      format.html
      format.json {render json: @category}
    end
  end
  def create

  end
  def destroy

  end

  private
  def fetch_category
    @category = Category.find(params[:id])
  end

end

app/controllers/soups_controller.rb
class SoupsController < ApplicationController
  before_action :fetch_soups, only: [:show, :edit, :update, :destroy, :toggle_featured]
	def index
		@soups = Soup.all

    respond_to do |format|
      format.html
      format.json {render json: @soups}
    end
  end

  def show
    respond_to do |format|
      format.json {render json: @soup}
      format.html
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  def toggle_featured
    @soup.toggle!(:featured)
    redirect_to @soup, notice: 'Successfully changed featured soup'
  end

  def secret_soups
    session[:vip] = true
    redirect_to root_path
  end
  private
  def fetch_soups
    @soup = Soup.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/soups_helper.rb
module SoupsHelper
end

app/views/categories/index.html.erb
<h1>Soup Categories</h1>
<ul>
  <% @categories.each do |category| %>
      <p><li><strong></strong><%= link_to category.name, category %> (<%= category.soups.count %>)</li></p>
  <% end %>
  <% if session[:vip] %>
      <li>Kale Based</li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1>Categories</h1>
<p>
  <%= @category.name %>
</p>

<p>
  <ul>
  <% @category.soups.each do |category| %>
 <li><%= link_to category.name, soup_path(category) %></li>

 <% end  %>
  </ul>
</p>
<p>
  <%= link_to 'Back to Categories', categories_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoupToBits</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/soups/index.html.erb
<h1> Soups </h1>
<% @soups.each do |soup| %>
<p><%= link_to soup.name, soup %></p>
<% end %>

app/views/soups/show.html.erb
<h1> <%= @soup.name %></h1>
<p>
  <% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>
  <% if @soup.featured? %>
<ul>
  <li>Featured Soup!</li>
</ul>
  <% end %>
</p>
<%= link_to 'Back to Soups', soups_path %> | <%= link_to 'Back to Categories', categories_path %>
<p>
  <%= link_to 'Toggle Featured!', toggle_featured_path(@soup) %>
</p>